baseURL = "https://ccdportfolio.netlify.app/"
languageCode = "en-us"
title = "The Portfolio Project"
theme = "minimal"
disqusShortname = "asa_ccd" # delete disable disqus comments
googleAnalytics = ""

[params]
    author = " "
    description = "A Professional Development Resource from the American Statistical Association Committee on Career Development"
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway"
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["r", "python", "shell", "html"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "https://community.amstat.org/ccd/home"
    name = "CCD"
    weight = 4

[[menu.main]]
    url = "https://amstat.org"
    name = "ASA"
    weight = 5
    
# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:philip.waggoner@yougov.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/pdwaggoner/ccdportfolio"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/AmstatNews/"
    name = "fab fa-twitter"
    weight = 3